[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = [
    "clippy",
    "--workspace",
    "--lib",
    "--bins",
    "--examples",
    "--",
    "-D",
    "warnings",
]

[tasks.test]
install_crate = "nextest"
command = "cargo"
args = ["nextest", "run", "--no-tests=pass"]

[tasks.doc-test]
workspace = false
command = "cargo"
args = ["test", "--doc", "-p", "rust-mcp-sdk"]
dependencies = ["doc-test-macros", "doc-test-transport"]

[tasks.doc-test-transport]
workspace = false
command = "cargo"
args = ["test", "--doc", "-p", "rust-mcp-sdk"]

[tasks.doc-test-macros]
workspace = false
command = "cargo"
args = ["test", "--doc", "-p", "rust-mcp-macros"]


[tasks.check]
dependencies = ["fmt", "clippy", "test", "doc-test"]

[tasks.clippy-fix]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]
